require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

def shared_pods
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

end


target 'TotApp' do
  shared_pods
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end

target 'TotApp-staging' do
  shared_pods
end

target 'TotApp-dev' do
  shared_pods
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'
